UP

diff --git a/.github/workflows/Actions_Build-Package.yml b/.github/workflows/Actions_Build-Package.yml
--- a/.github/workflows/Actions_Build-Package.yml
+++ b/.github/workflows/Actions_Build-Package.yml
@@ -1,49 +1,23 @@
 name: Actions Build and Package
 
 on:
-  repository_dispatch:
-  workflow_dispatch:
+  workflow_call:
     inputs:
-      ssh:
-        description: |
-          是否启用SSH连接?
-        required: false
-        default: false
-        type: boolean
-      
       version:
         description: |
           选择 OpenWrt 版本
-        required: true
-        default: "24.10.1"
-        type: choice
-        options:
-          - 23.05.5
-          - 24.10.1
+        required: false
+        type: string
       
       package_name:
         description: |
           选择编译插件
         required: false
-        default: "all"
-        type: choice
-        options:
-          - all
-          - api-static
-          - sub-static
-          - page-static
-          - napcat-api-static
-          - luci-app-cifs-mount
-          - luci-app-bypass
-          - luci-app-unishare
-          - luci-app-v2ray-server
-          - luci-app-sunpanel
-          - sunpanel
-          - api
+        type: string
 
 env:
   PACKAGE_NAME: ${{ inputs.package_name }}
-  CACHE_DIR: ~/cache
+  CACHE_DIR: ~/.cache
   TZ: Asia/Shanghai
   Download_URL: "https://downloads.openwrt.org/releases/${{ inputs.Version }}/targets"
   UPLOAD_BIN_DIR: false
@@ -62,7 +36,7 @@ jobs:
           echo "time=$(date "+%Y.%m.%d_%H%M%S")" >> $GITHUB_OUTPUT
 
   jod_build:
-    name: Build for ${{ matrix.arch }}
+    name: Build - Architecture: ${{ matrix.arch }}
     needs: jod_initial
     runs-on: ubuntu-latest
     strategy:
@@ -71,16 +45,16 @@ jobs:
         include:
           - arch: aarch64_generic
             sdk_url_path: layerscape/armv8_64b
-            sdk_name: -sdk-.*-layerscape-armv8_64b_
+            sdk_name: '-sdk-.*-layerscape-armv8_64b_'
           - arch: x86_64
             sdk_url_path: x86/64
-            sdk_name: -sdk-.*-x86-64_
+            sdk_name: '-sdk-.*-x86-64_'
 
     env:
       SDK_URL_PATH: ${{ matrix.sdk_url_path }}
       SDK_NAME: ${{ matrix.sdk_name }}
-      Time: ${{ needs.jod_initial.outputs.time }}
-      IPK_DIR: ${{ github.workspace }}/IPK
+      BUILD_TIME: ${{ needs.jod_initial.outputs.time }}
+      OUTPUT_DIR: ${{ github.workspace }}/Output/
       CONFIG_CCACHE: y
     steps: 
       - name: Checkout
@@ -88,74 +62,50 @@ jobs:
 
       - name: Install Dependencies
         run: |
-          DEBIAN_FRONTEND=noninteractive sudo apt-get install -y ccache gettext libncurses5-dev xsltproc
+          # DEBIAN_FRONTEND=noninteractive sudo apt-get install -y ccache gettext libncurses5-dev xsltproc
 
       - name: Setup Cache
         uses: actions/cache@main
         with:
-          path: |
-            ${{ env.CACHE_DIR }}
-          key: openwrt-${{ matrix.arch }}-${{ env.Time }}
-          restore-keys: |
-            openwrt-${{ matrix.arch }}-
+          path: ${{ env.CACHE_DIR }}
+          key: openwrt-${{ matrix.arch }}
 
-      - name: Create Directories
+      - name: Configure environment variables
         run: |
-          CACHE_DIR_SDK="$(eval echo "$CACHE_DIR/sdk")"
-          CACHE_DIR_DL="$(eval echo "$CACHE_DIR/dl")"
-          CACHE_DIR_FEEDS="$(eval echo "$CACHE_DIR/feeds")"
-          echo "CACHE_DIR_SDK: $CACHE_DIR_SDK"
-          echo "CACHE_DIR_DL: $CACHE_DIR_DL"
-          echo "CACHE_DIR_FEEDS: $CACHE_DIR_FEEDS"
-          test -d "$CACHE_DIR_SDK" || mkdir -p "$CACHE_DIR_SDK"
-          test -d "$CACHE_DIR_DL" || mkdir -p "$CACHE_DIR_DL"
-          test -d "$CACHE_DIR_FEEDS" || mkdir -p "$CACHE_DIR_FEEDS"
-          test -d "${{ env.IPK_DIR }}" || mkdir -p "${{ env.IPK_DIR }}"
-          echo "CACHE_DIR_SDK=$CACHE_DIR_SDK" >> $GITHUB_ENV
-          echo "CACHE_DIR_DL=$CACHE_DIR_DL" >> $GITHUB_ENV
-          echo "CACHE_DIR_FEEDS=$CACHE_DIR_FEEDS" >> $GITHUB_ENV
-          echo "SDK_HOME=$(mktemp -d)" >> $GITHUB_ENV
+          test -d "${{ env.CACHE_DIR }}" || mkdir -pm 755 "${{ env.CACHE_DIR }}"
 
       - name: Download and Unzip SDK
         run: |
-          cd "$CACHE_DIR_SDK"
-          if ! ( wget -q -O - "${Download_URL}/$SDK_URL_PATH/sha256sums" | grep -- "${{ env.SDK_NAME }}" > sha256sums.small 2>/dev/null ) ; then
-            echo "::error::Can not find ${{ env.SDK_NAME }} file in sha256sums."
-            exit 1
-          fi
-          SDK_FILE="$(cat sha256sums.small | cut -d' ' -f2 | sed 's/*//g')"
-          if ! sha256sum -c ./sha256sums.small >/dev/null 2>&1 ; then
-            wget -q -O "$SDK_FILE" "${Download_URL}/$SDK_URL_PATH/$SDK_FILE"
-            if ! sha256sum -c ./sha256sums.small >/dev/null 2>&1 ; then
-              echo "::error::SDK can not be verified!"
+          cd "${{ env.CACHE_DIR }}"
+          if [[ $(du -s "${{ env.CACHE_DIR }}" | awk '{ print $1}') -lt 10240 ]]; then
+            echo -e "\e[1;32m Start downloading the SDK \e[0m"
+            if ! ( wget -qO - "${Download_URL}/$SDK_URL_PATH/sha256sums" | grep -- "${{ env.SDK_NAME }}" > sha256sums.small 2>/dev/null ); then
+              echo -e "\e[1;31m Error:Can not find ${{ env.SDK_NAME }} file in sha256sums. \e[0m"
               exit 1
             fi
+            SDK_FILE="$(cat sha256sums.small | cut -d' ' -f2 | sed 's/*//g')"
+            if ! sha256sum -c ./sha256sums.small >/dev/null 2>&1 ; then
+              wget -qO "$SDK_FILE" "${Download_URL}/$SDK_URL_PATH/$SDK_FILE"
+              if ! sha256sum -c ./sha256sums.small >/dev/null 2>&1 ; then
+                echo -e "\e[1;31m Error:SDK can not be verified! \e[0m"
+                exit 1
+              fi
+            fi
+            tar -I zstd -xf "${SDK_FILE}" -C "${{ env.SDK_HOME }}" --strip=1 && rm -fr ${SDK_FILE}
           fi
-          cd -
-          file "$CACHE_DIR_SDK/$SDK_FILE"
-          # tar -I zstd -xvf "$CACHE_DIR_SDK/$SDK_FILE" -C "${{ env.SDK_HOME }}" --strip=1
-          tar -I zstd -xf "$CACHE_DIR_SDK/$SDK_FILE" -C "${{ env.SDK_HOME }}" --strip=1
-          cd "${{ env.SDK_HOME }}"
           test -d "dl" && rm -rf "dl" || true
           test -d "feeds" && rm -rf "feeds" || true
-          ln -s "$CACHE_DIR_DL" "dl"
-          ln -s "$CACHE_DIR_FEEDS" "feeds"
           cp feeds.conf.default feeds.conf
           sed -i 's#git.openwrt.org/openwrt/openwrt#github.com/openwrt/openwrt#' feeds.conf
           sed -i 's#git.openwrt.org/feed/packages#github.com/openwrt/packages#' feeds.conf
           sed -i 's#git.openwrt.org/project/luci#github.com/openwrt/luci#' feeds.conf
           sed -i 's#git.openwrt.org/feed/telephony#github.com/openwrt/telephony#' feeds.conf
-          cd -
-
+          echo "status=success" >> $GITHUB_OUTPUT
+          
       - name: Update and Install Packages
-        env:
-          OPENWRT_GOLANG_COMMIT: ${{ secrets.OPENWRT_GOLANG_COMMIT }}
         run: |
-          cd "${{ env.SDK_HOME }}"
-          ./scripts/feeds update -a >/dev/null 2>&1
-          test -d "feeds/packages/net/$PACKAGE_NAME" && rm -rf "feeds/packages/net/$PACKAGE_NAME" || true
-          test -d "feeds/packages/lang/golang" && rm -rf "feeds/packages/lang/golang" || true
-          curl https://codeload.github.com/openwrt/packages/tar.gz/${OPENWRT_GOLANG_COMMIT:-master} | tar -xz -C "feeds/packages/lang" --strip=2 packages-${OPENWRT_GOLANG_COMMIT:-master}/lang/golang
+          cd "${{ env.CACHE_DIR }}"
+          # ./scripts/feeds update -a >/dev/null 2>&1
           find "${{ github.workspace }}" -maxdepth 1 -exec ln -s {} "package/" \;
           rm package/$(basename ${{ github.workspace }})
           ./scripts/feeds install -a >/dev/null 2>&1
@@ -200,27 +150,3 @@ jobs:
           tag_name: ${{ env.Time }}
           body_path: release.txt
           files: ${{ env.IPK_DIR }}/*.ipk
-
-      - name: SSH connection to Actions
-        if: (inputs.ssh == true) || contains(github.event.action, 'ssh')
-        uses: mxschmitt/action-tmate@v3  
-
-  jod_notify:
-    name: Notify Release Publish
-    runs-on: ubuntu-latest
-    env:
-      TRIGGER_URL: ${{ secrets.TRIGGER_URL }}
-      TRIGGER_TOKEN: ${{ secrets.TRIGGER_TOKEN }}
-    needs: jod_build
-    steps:
-      - name: Notify Jenkins
-        run: |
-          if [ -z "$TRIGGER_URL" ] ; then
-            echo "::warning::No trigger url found, skip..."
-            exit 0
-          fi
-          curl -X POST \
-              -H "Content-Type: application/json; charset=utf-8" \
-              -H "Authorization: Bearer $TRIGGER_TOKEN" \
-              -d "{\"event\":\"release\",\"repository\":\"${{ github.repository }}\",\"ref\":\"${{ github.ref }}\"}" \
-              "$TRIGGER_URL" || true
